# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: AAAduck.VaultGuard
PackageVersion: 2.3.0
InstallerType: portable
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/AAAduck/VaultGuard/releases/download/v2.3.0/VaultGuard.exe
  InstallerSha256: BDDCC96F8ABDF7113FE524ABD0E27E0C906F50618679B8172EF100B276A2745E
  Commands:
  - VaultGuard
ManifestType: installer
ManifestVersion: 1.6.0
