# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: AAAduck.VaultGuard
PackageVersion: 2.1.0
InstallerType: portable
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/AAAduck/VaultGuard/releases/download/v2.1.0/VaultGuard.exe
  InstallerSha256: 3EBD78CD193D426C20ED9BFA12460547216254DF3B545453D12A4FC51EC06D1E
  Commands:
  - VaultGuard
ManifestType: installer
ManifestVersion: 1.6.0
