# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: AAAduck.VaultGuard
PackageVersion: 2.2.0
InstallerType: portable
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/AAAduck/VaultGuard/releases/download/v2.2.0/VaultGuard.exe
  InstallerSha256: 985A4090CBD55FC33DB3AD4B2BC2E52CB4794F3EB86BE82C339075F38647597E
  Commands:
  - VaultGuard
ManifestType: installer
ManifestVersion: 1.6.0
